services:
  # Backend API Service
  - type: web
    name: plivo-mini-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plivo-mini-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: plivo-mini-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # Redis Cache
  - type: redis
    name: plivo-mini-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# PostgreSQL Database
databases:
  - name: plivo-mini-db
    plan: free
